import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useEffect, useRef, useState } from 'react';
import * as socketIO from 'socket.io-client';
import { DefaultEventsMap } from '@socket.io/component-emitter';
import { Socket } from 'socket.io-client/build/esm/socket';

const host = "http://localhost:8000";

export default function Home() {
  const socketRef = useRef<Socket<DefaultEventsMap, DefaultEventsMap>>();
  const [ id, setId ] = useState('');

  const ConnectServer = () => {
    socketRef.current = socketIO.connect(host);
    
    console.log('connect');

    socketRef.current.emit('createPlayer', 'Hà Nhật Tuấn');
    socketRef.current.on('errorCreatePlayer', data => {
      console.log(data);
      Disconnect();
    })

    socketRef.current.on('getId', data => {
      setId(data);
      console.log(data);
    });
  }

  const Disconnect = () => {
    socketRef.current?.disconnect();
    console.log('disconnect!');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className={styles.button} onClick={ConnectServer}>Connect</button>
      <button className={styles.button} onClick={Disconnect}>Disconnect</button>
    </>
  )
}
